version: "3"

services:
  php:
    container_name: laracomloc-php
    build:
      context: .docker
      dockerfile: laracomloc-php/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=i53weLzCSdunQzNc2SXR2AE9XJVDuNaq
      - DB_HOST=db
      - DB_DATABASE=laracomloc
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 9000
    depends_on:
      - db

  db:
    container_name: laracomloc-db
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 33071:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laracomloc
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  nginx:
    container_name: laracomloc-nginx
    image: nginx:1.17
    links:
      - php
    ports:
      - 80:80
    volumes:
      - .docker/laracomloc-nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laracomloc-phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
volumes:
  mysql: